/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : ViewTest
 * Author          : <YourName>
 * Created Date    : Feb 16, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Feb 16, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Feb 16, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

public class ViewTest {

	@AuraEnabled(cacheable=true)
	public static void doSomething() {
		// Your logic here
	}

}